# Generated by Django 5.2.4 on 2025-09-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_modelsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsuggestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото автомобиля (по желанию)', null=True, upload_to='suggested_cars/', verbose_name='Фото автомобиля'),
        ),
        migrations.AlterField(
            model_name='modelsuggestion',
            name='description',
            field=models.TextField(help_text='Почему эта модель культовая?', verbose_name='Описание'),
        ),
    ]
