# Generated by Django 5.2.4 on 2025-09-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_modelsuggestion_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsuggestion',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Уведомлен'),
        ),
    ]
