# Generated by Django 5.2.4 on 2025-08-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_brand_logo'),
        ('cars', '0004_auto_20250814_2051'),
    ]

    operations = [
    ]
